# Pinky rice (night) — kitty. Подключается из kitty.conf: include kitty-pinky.conf
font_family      JetBrains Mono
font_size        21.0

hide_window_decorations yes
window_padding_width 12

background            #1c1720
background_opacity    0.90
foreground            #e6d3dc
cursor                #e7a3bf
cursor_text_color     #1c1720
selection_background  #8f5f78
selection_foreground  #f5e6ee
url_color             #e7a3bf

color0   #2b2430
color8   #5c4f5f
color1   #e0788f
color9   #eb96a8
color2   #8fc7a0
color10  #a9d9b7
color3   #e0b27a
color11  #ecc899
color4   #8ea9d6
color12  #a9c0e4
color5   #c98ba6
color13  #e7a3bf
color6   #88c1c7
color14  #a5d4d8
color7   #cbb8c2
color15  #f0e2e9

# закрывать окно без вопроса
confirm_os_window_close 0
